apiVersion: v2
name: siaap-helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies: # A list of the chart requirements (optional)
  - name: airflow
    version: "1.14.0"
    repository: "https://airflow.apache.org"
    condition: airflow.enabled
    
  - name: minio
    version: "5.2.0"
    repository: "https://charts.min.io/"
    condition: minio.enabled
    alias: minio
  
  - name: redis-stack-server
    version: "0.4.12"
    repository: "https://redis-stack.github.io/helm-redis-stack/"
    condition: redis.enabled
    alias: redis
  - name: neo4j
    version: "5.21.0"
    repository: "https://helm.neo4j.com/neo4j"
    condition: neo4j.enabled
    alias: neo4j
  - name: mongodb
    version: "15.6.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
    alias: mongodb

